# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android) # Or :ios, depending on your primary platform

platform :android do
  desc "Runs all the Android tests"
  lane :testAndroid do
    gradle(task: "clean")
    gradle(task: ":network:testDebugUnitTest") # Run Android unit tests
  end
end

platform :ios do
  desc "Runs all the iOS tests"
   lane :testIOS do
       gradle(task: "clean")
       gradle(task: ":network:iosSimulatorArm64Test") # Run iOS unit tests
     end
end

# --- Release Lanes ---

desc "Creates and pushes a tag on GitLab"
lane :tag_release do
    # This lane automates the process of creating and pushing a tag to the GitLab repository.
    # It extracts the version number from the Gradle output, creates a Git tag, and pushes it to the remote repository.

    # Get the version name from the Gradle output.
    result = gradle(task: "-q :network:printVersionName", print_command: false, print_command_output: true)
    # The 'gradle' action is used to execute a Gradle task.
    #   - '-q' flag: Runs Gradle in quiet mode.
    #   - ':network:printVersionName': The specific Gradle task to run, which prints the version name.
    #   - 'print_command: false': Prevents the Gradle command from being printed to the console.
    #   - 'print_command_output: true': Prints the output of the Gradle command to the console.

    # Extract version number using a regular expression.
    version_match = result.match(/(\d+\.\d+\.\d+)/) # Match a pattern like "1.0.0"
    version_name = version_match[1] if version_match # Extracts the version number from the match.

    # Configure Git user (if needed).
    sh("git config --global user.email \"ricardo.dasilva@paydock.com\"") # Sets the Git user email.
    sh("git config --global user.name \"Ricardo\"") # Sets the Git user name.
    # The 'sh' action is used to execute shell commands.

    # Create and push the tag.
    sh("git tag -a #{version_name} -m \"Release version #{version_name}\"") # Creates an annotated Git tag.
    #   - '-a': Creates an annotated tag.
    #   - '#{version_name}': The tag name (e.g., "1.0.0").
    #   - '-m': Specifies the tag message.

    # Use the GITLAB_TOKEN environment variable for authentication.
    git_url_with_token = "https://gitlab-ci-token:#{ENV['GITLAB_TOKEN']}@gitlab.com/paydock/bounded-contexts/mobile/mobile-lib-networking-android.git"
    sh("git remote set-url origin #{git_url_with_token}") # Updates the remote URL to include the token.
    #   - 'ENV['GITLAB_TOKEN']': Accesses the 'GITLAB_TOKEN' environment variable.

    # Push the tag to the remote repository.
    sh("git push origin #{version_name}") # Pushes the tag to the remote repository.
end

desc "Creates a release on GitLab"
lane :create_gitlab_release do |options|
    # This lane automates the process of creating a release on GitLab.
    # It is designed to be triggered when a new tag is pushed to the 'release' branch.

    # Extract the version tag from the options, environment variables, or Git tags.
    # If 'version' is passed as an option, it's used; otherwise, CI_COMMIT_TAG is checked.
    # If neither is available, it falls back to the latest Git tag.
    version_tag = options[:version] || ENV["CI_COMMIT_TAG"] || sh("git describe --tags --abbrev=0").strip
    # Remove the leading 'v' from the version tag if present.
    version_tag = version_tag.gsub(/^v/, '')

    # Ensure a version tag is available; otherwise, raise an error.
    unless version_tag
        UI.user_error!("No version tag provided. Ensure you pass 'version' as an option or set CI_COMMIT_TAG.")
    end

    # Extract information from environment variables.
    # These variables are typically set by the CI/CD pipeline.
    tag_name = ENV["CI_COMMIT_TAG"] # The tag name from the CI/CD environment.
    project_id = ENV["CI_PROJECT_ID"] # The project ID from the CI/CD environment.
    gitlab_token = ENV["GITLAB_TOKEN"] # The GitLab API token from the CI/CD environment.
    api_endpoint = ENV["CI_API_V4_URL"] # The GitLab API endpoint from the CI/CD environment.

    # Read the changelog file to get the release notes for the specified version.
    changelog_notes = get_release_notes(version_tag)

    # Construct the release details.
    # This includes the release name and a description that includes the changelog notes.
    release_name = "Release: v#{version_tag}" # The name of the release.
    release_description = <<~RELEASE
        #{changelog_notes}

        **Full Changelog:** [View on GitLab](https://gitlab.com/paydock/bounded-contexts/mobile/mobile-lib-networking-android/-/commits/#{version_tag})
    RELEASE

    # Construct the release data payload.
    # This is the data that will be sent to the GitLab API to create the release.
    release_data = {
        "name" => release_name, # The name of the release.
        "tag_name" => version_tag, # The tag name of the release.
        "description" => release_description, # The description of the release.
        "ref" => version_tag # The reference (tag or branch) for the release.
    }.to_json # Convert the data to JSON format.

    # Construct the correct API URL.
    # This is the URL that will be used to create the release via the GitLab API.
    api_url = "#{api_endpoint}/projects/#{project_id}/releases"

    # Create the release using the GitLab API. https://docs.gitlab.com/api/releases/
    # This uses the 'curl' command to send a POST request to the GitLab API.
    # --silent: Suppresses progress output.
    # --header: Specifies the headers for the request (Content-Type and PRIVATE-TOKEN).
    # --data: Specifies the data payload for the request (the release data in JSON format).
    # --request POST: Specifies that this is a POST request.
    response = sh("curl --silent --header 'Content-Type: application/json' --header 'PRIVATE-TOKEN: #{gitlab_token}' \
        --data '#{release_data}' \
        --request POST '#{api_url}'")

    # Output the GitLab API response for debugging purposes.
    puts "📢 GitLab API Response: #{response}"

    # Indicate that the GitLab release was created successfully.
    UI.success("✅ GitLab release created successfully: #{release_name}")
end

desc "Creates a release on GitHub"
lane :create_github_release do |options|
    # This lane automates the process of creating a release on GitHub.
    # It extracts the version name from the Git tag, authenticates with GitHub, and creates a new release.

    # Extract version name from tag (assuming tags are in the format "v1.0.0").
    version_tag = options[:version] || ENV["CI_COMMIT_TAG"] || sh("git describe --tags --abbrev=0").strip
    # The 'sh' action is used to execute shell commands.
    #   - 'git describe --tags --abbrev=0': Gets the latest tag name.
    #   - '.strip': Removes leading/trailing whitespace.

    require 'octokit' # Loads the Octokit library for interacting with the GitHub API.

    # Authenticate with GitHub (assuming GITHUB_TOKEN is set in your CI/CD variables).
    # Set up Octokit client.
    client = Octokit::Client.new(access_token: ENV['GITHUB_TOKEN']) # Creates an Octokit client.

    # Get release notes from CHANGELOG.md
    release_notes = get_release_notes(version_tag)

    # Create a release on GitHub.
    repo = 'PayDock/android-core-networking' # Replace with your GitHub repository
    release_name = "v#{version_tag}" # Creates the release name (e.g., "v1.0.0").
    release_body = <<~RELEASE
        #{release_notes}

        **Full Changelog:** [View on GitLab](https://github.com/PayDock/android-core-networking/commits/#{version_tag})
    RELEASE

    release = client.create_release(repo, "#{version_tag}", { # Creates the release on GitHub.
      tag_name: "#{version_tag}", # Sets the tag name.
      name: release_name, # Sets the release name.
      body: release_body, # Sets the release body.
      is_generate_release_notes: false, # Disables automatic generation of release notes.
      make_latest: 'true' # Marks the release as the latest.
    })
    # The 'client.create_release' method is used to create the release.
end

# Extracts the release notes for a specific version from the CHANGELOG.md file.
#
# @param version [String] The version number to extract release notes for (e.g., "2.3.0").
# @return [String] The release notes for the specified version, or an empty string if no entry is found.
def get_release_notes(version)
    # Read the changelog file
    changelog_path = "../CHANGELOG.md"
    changelog_content = File.read(changelog_path)
    match = changelog_content.match(/^##\s+\[#{Regexp.escape(version)}\].*?\n(.*?)(?=\n##\s+\[|\z)/m)
    if match
      return match[1].strip
    else
      UI.message("⚠️ No changelog entry found for version #{version}.")
      return "" # Return an empty string if no changelog entry is found
    end
end

# Extracts the changelog content for a specific version from a given changelog content string.
#
# This function is a helper function that is used by `get_release_notes`.
# It takes the entire changelog content as a string and the version to search for.
# It then uses a regular expression to find the section of the changelog that corresponds to the given version.
#
# @param changelog_content [String] The entire content of the changelog file as a string.
# @param version [String] The version number to extract changelog content for (e.g., "2.3.0").
# @return [String] The changelog content for the specified version, or a message indicating no entry was found.
def extract_changelog_for_version(changelog_content, version)
    match = changelog_content.match(/^##\s+\[#{Regexp.escape(version)}\].*?\n(.*?)(?=\n##\s+\[|\z)/m)
    if match
      return match[1].strip
    else
      return "No changelog entry found for version #{version}"
    end
end

# --- Publish Lanes ---

desc "Publishes the SDK to GitHub Packages"
lane :publish_to_github do
    # This lane publishes the built SDK to GitHub Packages.
    # It uses the 'gradle' action to execute the 'publishAllPublicationsToGitHubPackagesRepository' Gradle task.
     gradle(task: ":network:publishAllPublicationsToGitHubPackagesRepository")
end
